#pragma once

#define AIS_MESSAGE_POSITION_REPORT_SOTDMA      1
#define AIS_MESSAGE_POSITION_REPORT_SOTDMA2     2
#define AIS_MESSAGE_POSITION_REPORT_ITDMA       3
#define AIS_MESSAGE_BASE_STATION_REPORT         4
#define AIS_MESSAGE_SHIP_STATIC_INFO            5

